"""Constants for USFM references."""

BOOK_CANON = {
    "GEN": "ot",
    "EXO": "ot",
    "LEV": "ot",
    "NUM": "ot",
    "DEU": "ot",
    "JOS": "ot",
    "JDG": "ot",
    "RUT": "ot",
    "1SA": "ot",
    "2SA": "ot",
    "1KI": "ot",
    "2KI": "ot",
    "1CH": "ot",
    "2CH": "ot",
    "EZR": "ot",
    "NEH": "ot",
    "EST": "ot",
    "JOB": "ot",
    "PSA": "ot",
    "PRO": "ot",
    "ECC": "ot",
    "SNG": "ot",
    "ISA": "ot",
    "JER": "ot",
    "LAM": "ot",
    "EZK": "ot",
    "DAN": "ot",
    "HOS": "ot",
    "JOL": "ot",
    "AMO": "ot",
    "OBA": "ot",
    "JON": "ot",
    "MIC": "ot",
    "NAM": "ot",
    "HAB": "ot",
    "ZEP": "ot",
    "HAG": "ot",
    "ZEC": "ot",
    "MAL": "ot",
    "MAT": "nt",
    "MRK": "nt",
    "LUK": "nt",
    "JHN": "nt",
    "ACT": "nt",
    "ROM": "nt",
    "1CO": "nt",
    "2CO": "nt",
    "GAL": "nt",
    "EPH": "nt",
    "PHP": "nt",
    "COL": "nt",
    "1TH": "nt",
    "2TH": "nt",
    "1TI": "nt",
    "2TI": "nt",
    "TIT": "nt",
    "PHM": "nt",
    "HEB": "nt",
    "JAS": "nt",
    "1PE": "nt",
    "2PE": "nt",
    "1JN": "nt",
    "2JN": "nt",
    "3JN": "nt",
    "JUD": "nt",
    "REV": "nt",
    "TOB": "ap",
    "JDT": "ap",
    "ESG": "ap",
    "WIS": "ap",
    "SIR": "ap",
    "BAR": "ap",
    "LJE": "ap",
    "S3Y": "ap",
    "SUS": "ap",
    "BEL": "ap",
    "1MA": "ap",
    "2MA": "ap",
    "3MA": "ap",
    "4MA": "ap",
    "1ES": "ap",
    "2ES": "ap",
    "MAN": "ap",
    "PS2": "ap",
    "ODA": "ap",
    "PSS": "ap",
    "3ES": "ap",
    "EZA": "ap",
    "5EZ": "ap",
    "6EZ": "ap",
    "DAG": "ap",
    "PS3": "ap",
    "2BA": "ap",
    "LBA": "ap",
    "JUB": "ap",
    "ENO": "ap",
    "1MQ": "ap",
    "2MQ": "ap",
    "3MQ": "ap",
    "REP": "ap",
    "4BA": "ap",
    "LAO": "ap",
    "LKA": "nt",  # luke-acts combo
}
BOOKS = list(BOOK_CANON.keys())
NT_BOOKS = [book for book in BOOKS if BOOK_CANON[book] == "nt"]
OT_BOOKS = [book for book in BOOKS if BOOK_CANON[book] == "ot"]

# English book names and common abbreviations, mapped to USFM codes.
# Keys are normalized: lowercased, with all non-alphanumeric characters
# stripped, so "Genesis", "genesis", "Gen", and "Gen." all reduce to "gen".
# Numbered books (1/2/3 Samuel, Kings, ... John, Maccabees, Esdras) are NOT
# pre-expanded here; convert_book_name_to_usfm peels the leading ordinal and
# resolves the remainder via NUMBERED_BOOKS below.
BOOK_NAMES = {
    "genesis": "GEN",
    "gen": "GEN",
    "gn": "GEN",
    "exodus": "EXO",
    "exod": "EXO",
    "exo": "EXO",
    "ex": "EXO",
    "leviticus": "LEV",
    "lev": "LEV",
    "lv": "LEV",
    "numbers": "NUM",
    "num": "NUM",
    "nm": "NUM",
    "deuteronomy": "DEU",
    "deut": "DEU",
    "deu": "DEU",
    "dt": "DEU",
    "joshua": "JOS",
    "josh": "JOS",
    "jos": "JOS",
    "jsh": "JOS",
    "judges": "JDG",
    "judg": "JDG",
    "jdg": "JDG",
    "jdgs": "JDG",
    "ruth": "RUT",
    "rut": "RUT",
    "rth": "RUT",
    "ezra": "EZR",
    "ezr": "EZR",
    "nehemiah": "NEH",
    "neh": "NEH",
    "esther": "EST",
    "esth": "EST",
    "est": "EST",
    "job": "JOB",
    "jb": "JOB",
    "psalms": "PSA",
    "psalm": "PSA",
    "psa": "PSA",
    "pss": "PSA",
    "psm": "PSA",
    "ps": "PSA",
    "proverbs": "PRO",
    "prov": "PRO",
    "pro": "PRO",
    "prv": "PRO",
    "ecclesiastes": "ECC",
    "eccles": "ECC",
    "eccl": "ECC",
    "ecc": "ECC",
    "qoh": "ECC",
    "qoheleth": "ECC",
    "songofsongs": "SNG",
    "songofsolomon": "SNG",
    "song": "SNG",
    "sng": "SNG",
    "sos": "SNG",
    "canticles": "SNG",
    "cant": "SNG",
    "isaiah": "ISA",
    "isa": "ISA",
    "jeremiah": "JER",
    "jer": "JER",
    "lamentations": "LAM",
    "lam": "LAM",
    "ezekiel": "EZK",
    "ezek": "EZK",
    "ezk": "EZK",
    "eze": "EZK",
    "daniel": "DAN",
    "dan": "DAN",
    "dn": "DAN",
    "hosea": "HOS",
    "hos": "HOS",
    "joel": "JOL",
    "jol": "JOL",
    "jl": "JOL",
    "amos": "AMO",
    "amo": "AMO",
    "obadiah": "OBA",
    "obad": "OBA",
    "oba": "OBA",
    "ob": "OBA",
    "jonah": "JON",
    "jon": "JON",
    "jnh": "JON",
    "micah": "MIC",
    "mic": "MIC",
    "nahum": "NAM",
    "nah": "NAM",
    "nam": "NAM",
    "habakkuk": "HAB",
    "hab": "HAB",
    "hb": "HAB",
    "zephaniah": "ZEP",
    "zeph": "ZEP",
    "zep": "ZEP",
    "haggai": "HAG",
    "hag": "HAG",
    "hg": "HAG",
    "zechariah": "ZEC",
    "zech": "ZEC",
    "zec": "ZEC",
    "malachi": "MAL",
    "mal": "MAL",
    "matthew": "MAT",
    "matt": "MAT",
    "mat": "MAT",
    "mt": "MAT",
    "mark": "MRK",
    "mrk": "MRK",
    "mar": "MRK",
    "mk": "MRK",
    "luke": "LUK",
    "luk": "LUK",
    "lk": "LUK",
    "john": "JHN",
    "jhn": "JHN",
    "jn": "JHN",
    "acts": "ACT",
    "act": "ACT",
    "romans": "ROM",
    "rom": "ROM",
    "galatians": "GAL",
    "gal": "GAL",
    "ephesians": "EPH",
    "eph": "EPH",
    "philippians": "PHP",
    "phil": "PHP",
    "php": "PHP",
    "colossians": "COL",
    "col": "COL",
    "titus": "TIT",
    "tit": "TIT",
    "philemon": "PHM",
    "philem": "PHM",
    "phlm": "PHM",
    "phm": "PHM",
    "hebrews": "HEB",
    "heb": "HEB",
    "james": "JAS",
    "jas": "JAS",
    "jude": "JUD",
    "jud": "JUD",
    "revelation": "REV",
    "rev": "REV",
    "rv": "REV",
    "apocalypse": "REV",
    "apoc": "REV",
    "tobit": "TOB",
    "tob": "TOB",
    "tb": "TOB",
    "judith": "JDT",
    "jdt": "JDT",
    "jdth": "JDT",
    "wisdomofsolomon": "WIS",
    "wisdom": "WIS",
    "wis": "WIS",
    "wissol": "WIS",
    "sirach": "SIR",
    "ecclesiasticus": "SIR",
    "sir": "SIR",
    "bensira": "SIR",
    "baruch": "BAR",
    "bar": "BAR",
    "letterofjeremiah": "LJE",
    "letjer": "LJE",
    "lje": "LJE",
    "epistleofjeremiah": "LJE",
    "songofthethreeyoungmen": "S3Y",
    "songofthree": "S3Y",
    "prayerofazariah": "S3Y",
    "praz": "S3Y",
    "s3y": "S3Y",
    "susanna": "SUS",
    "sus": "SUS",
    "belandthedragon": "BEL",
    "bel": "BEL",
    "prayerofmanasseh": "MAN",
    "prman": "MAN",
}

# Numbered books: each stem (full name + abbreviations) stored once, mapped
# to {ordinal: USFM}. convert_book_name_to_usfm normalizes a leading ordinal
# (arabic 1/2/3, roman I/II/III, or word First/Second/Third) to an int, then
# looks the remaining stem up here. An out-of-range ordinal (e.g. 4 John) or a
# malformed one (e.g. IIV) finds no entry and yields None.
NUMBERED_BOOKS = {
    "samuel": {1: "1SA", 2: "2SA"},
    "sam": {1: "1SA", 2: "2SA"},
    "sa": {1: "1SA", 2: "2SA"},
    "sm": {1: "1SA", 2: "2SA"},
    "kings": {1: "1KI", 2: "2KI"},
    "kgs": {1: "1KI", 2: "2KI"},
    "kg": {1: "1KI", 2: "2KI"},
    "ki": {1: "1KI", 2: "2KI"},
    "chronicles": {1: "1CH", 2: "2CH"},
    "chron": {1: "1CH", 2: "2CH"},
    "chr": {1: "1CH", 2: "2CH"},
    "ch": {1: "1CH", 2: "2CH"},
    "corinthians": {1: "1CO", 2: "2CO"},
    "cor": {1: "1CO", 2: "2CO"},
    "co": {1: "1CO", 2: "2CO"},
    "thessalonians": {1: "1TH", 2: "2TH"},
    "thess": {1: "1TH", 2: "2TH"},
    "thes": {1: "1TH", 2: "2TH"},
    "th": {1: "1TH", 2: "2TH"},
    "timothy": {1: "1TI", 2: "2TI"},
    "tim": {1: "1TI", 2: "2TI"},
    "ti": {1: "1TI", 2: "2TI"},
    "peter": {1: "1PE", 2: "2PE"},
    "pet": {1: "1PE", 2: "2PE"},
    "pe": {1: "1PE", 2: "2PE"},
    "john": {1: "1JN", 2: "2JN", 3: "3JN"},
    "jn": {1: "1JN", 2: "2JN", 3: "3JN"},
    "jhn": {1: "1JN", 2: "2JN", 3: "3JN"},
    "jo": {1: "1JN", 2: "2JN", 3: "3JN"},
    "maccabees": {1: "1MA", 2: "2MA"},
    "macc": {1: "1MA", 2: "2MA"},
    "mac": {1: "1MA", 2: "2MA"},
    "ma": {1: "1MA", 2: "2MA"},
    "esdras": {1: "1ES", 2: "2ES"},
    "esd": {1: "1ES", 2: "2ES"},
    "es": {1: "1ES", 2: "2ES"},
}

ORDINAL_WORDS = {"first": 1, "second": 2, "third": 3}
ROMAN_ORDINALS = {"i": 1, "ii": 2, "iii": 3}
